"""The notification-area icon and its menu.

The tray icon is rendered live from the same `draw_avatar` code as the floating
window, so the two never drift apart and the tray can follow the mood. The
shortcut/Alt+Tab icon is different: Windows wants a real .ico file on disk, so
`app_icon` loads the one generated by tools/make_icon.py.
"""

from __future__ import annotations

from pathlib import Path

from PySide6.QtCore import QObject, Qt, Signal
from PySide6.QtGui import QIcon, QPainter, QPixmap
from PySide6.QtWidgets import QMenu, QSystemTrayIcon

from .branding import APP_NAME
from .config import Config
from .features.monitor import Mood, Sample
from .features.timers import Reminder, TimerManager
from .sprite import SpriteState, draw_avatar

_ICON_SIZE = 64  # rendered once per mood, then scaled down by Qt


ICON_FILE = Path(__file__).resolve().parent / "app.ico"


def app_icon() -> QIcon:
    """The application icon, used for shortcuts, dialogs and Alt+Tab.

    Regenerate it with `python tools/make_icon.py` after changing sprite.py.
    Falls back to a freshly drawn one if the file is missing, so a stripped
    install still shows a sensible icon rather than a blank square.
    """
    if ICON_FILE.exists():
        icon = QIcon(str(ICON_FILE))
        if not icon.isNull():
            return icon
    return mood_icon(Mood.CALM)


def mood_icon(mood: Mood) -> QIcon:
    pixmap = QPixmap(_ICON_SIZE, _ICON_SIZE)
    pixmap.fill(Qt.GlobalColor.transparent)
    painter = QPainter(pixmap)
    # A neutral pose: a tray icon that animates is just distracting.
    draw_avatar(painter, _ICON_SIZE, SpriteState(mood=mood, time=0.0))
    painter.end()
    return QIcon(pixmap)


class TrayIcon(QObject):
    """Owns the QSystemTrayIcon and rebuilds its menu on demand."""

    quick_note_requested = Signal()
    capture_region_requested = Signal()
    clipboard_requested = Signal()
    notes_requested = Signal()
    reminder_requested = Signal()
    launch_requested = Signal(object)  # LauncherEntry
    cancel_timer_requested = Signal(int)
    toggle_avatar_requested = Signal()
    snap_requested = Signal()
    reset_position_requested = Signal()
    reload_config_requested = Signal()
    open_config_folder_requested = Signal()
    autostart_toggled = Signal(bool)
    clipboard_capture_toggled = Signal(bool)
    quit_requested = Signal()

    def __init__(self, config: Config, timers: TimerManager, parent=None) -> None:
        super().__init__(parent)
        self._config = config
        self._timers = timers
        self._status_text = "Démarrage…"
        self._mood = Mood.CALM
        self._avatar_visible = True
        self._autostart = False
        self._capture_clipboard = config.clipboard.enabled

        self._icon = QSystemTrayIcon(mood_icon(Mood.CALM), self)
        self._icon.setToolTip(APP_NAME)
        self._icon.activated.connect(self._on_activated)

        self._menu = QMenu()
        # Rebuilding on aboutToShow keeps live data (status, timers) accurate
        # without a second timer just to refresh menu text.
        self._menu.aboutToShow.connect(self._rebuild_menu)
        self._icon.setContextMenu(self._menu)

    def show(self) -> None:
        self._icon.show()

    def hide(self) -> None:
        self._icon.hide()

    def apply_config(self, config: Config) -> None:
        self._config = config
        self._capture_clipboard = config.clipboard.enabled

    def set_avatar_visible(self, visible: bool) -> None:
        self._avatar_visible = visible

    def set_autostart(self, enabled: bool) -> None:
        self._autostart = enabled

    def set_clipboard_capture(self, enabled: bool) -> None:
        self._capture_clipboard = enabled

    def update_status(self, sample: Sample, mood: Mood) -> None:
        self._status_text = sample.summary()
        self._icon.setToolTip(f"{APP_NAME}\n{self._status_text}")
        if mood is not self._mood:
            self._mood = mood
            self._icon.setIcon(mood_icon(mood))

    def notify(self, title: str, body: str, warning: bool = False) -> None:
        icon = (
            QSystemTrayIcon.MessageIcon.Warning
            if warning
            else QSystemTrayIcon.MessageIcon.Information
        )
        self._icon.showMessage(title, body, icon, 5000)

    def popup_menu(self, position) -> None:
        self._rebuild_menu()
        self._menu.popup(position)

    def launcher_menu(self, parent: QMenu | None = None) -> QMenu:
        menu = QMenu("Lancer", parent)
        if not self._config.launcher:
            action = menu.addAction("Aucune entrée dans config.toml")
            action.setEnabled(False)
            return menu
        for entry in self._config.launcher:
            action = menu.addAction(entry.label)
            action.triggered.connect(
                lambda _=False, item=entry: self.launch_requested.emit(item)
            )
        return menu

    # -- internals --------------------------------------------------------

    def _on_activated(self, reason: QSystemTrayIcon.ActivationReason) -> None:
        if reason in (
            QSystemTrayIcon.ActivationReason.Trigger,
            QSystemTrayIcon.ActivationReason.DoubleClick,
        ):
            self.clipboard_requested.emit()

    def _rebuild_menu(self) -> None:
        menu = self._menu
        menu.clear()

        status = menu.addAction(self._status_text)
        status.setEnabled(False)
        menu.addSeparator()

        hotkeys = self._config.hotkeys
        self._add(
            menu,
            "Montrer une zone…",
            self.capture_region_requested,
            hotkeys.capture_region,
        )
        self._add(menu, "Note rapide", self.quick_note_requested, hotkeys.quick_note)
        self._add(
            menu, "Presse-papiers", self.clipboard_requested, hotkeys.clipboard
        )
        self._add(menu, "Notes", self.notes_requested)
        self._add(menu, "Me rappeler…", self.reminder_requested)

        menu.addSeparator()
        menu.addMenu(self.launcher_menu(menu))

        active = self._timers.active
        if active:
            timers_menu = menu.addMenu(f"Minuteurs ({len(active)})")
            for reminder in active:
                self._add_timer_entry(timers_menu, reminder)
            timers_menu.addSeparator()
            timers_menu.addAction("Tout annuler").triggered.connect(
                self._timers.cancel_all
            )

        menu.addSeparator()
        toggle = menu.addAction(
            "Masquer le lutin" if self._avatar_visible else "Afficher le lutin"
        )
        toggle.triggered.connect(self.toggle_avatar_requested.emit)
        menu.addAction("Replacer sur la barre").triggered.connect(
            self.snap_requested.emit
        )
        menu.addAction("Oublier la position enregistrée").triggered.connect(
            self.reset_position_requested.emit
        )

        capture = menu.addAction("Enregistrer le presse-papiers")
        capture.setCheckable(True)
        capture.setChecked(self._capture_clipboard)
        capture.toggled.connect(self.clipboard_capture_toggled.emit)

        autostart = menu.addAction("Lancer au démarrage de Windows")
        autostart.setCheckable(True)
        autostart.setChecked(self._autostart)
        autostart.toggled.connect(self.autostart_toggled.emit)

        menu.addSeparator()
        menu.addAction("Recharger la configuration").triggered.connect(
            self.reload_config_requested.emit
        )
        menu.addAction("Ouvrir le dossier de configuration").triggered.connect(
            self.open_config_folder_requested.emit
        )
        menu.addSeparator()
        menu.addAction("Quitter").triggered.connect(self.quit_requested.emit)

    def _add(self, menu: QMenu, text: str, signal, shortcut_hint: str = "") -> None:
        label = f"{text}\t{shortcut_hint}" if shortcut_hint else text
        menu.addAction(label).triggered.connect(signal.emit)

    def _add_timer_entry(self, menu: QMenu, reminder: Reminder) -> None:
        action = menu.addAction(f"{reminder.remaining_text}  -  {reminder.label}")
        action.triggered.connect(
            lambda _=False, rid=reminder.id: self.cancel_timer_requested.emit(rid)
        )
